name: toml
version: 0.6.1
description: Parser and encoder for TOML v0.4.0 (Tom's Obvious, Minimal Language) configuration files.
repository: https://github.com/just95/toml.dart
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  path: ^1.7.0
  petitparser: ^3.1.0
  quiver: ^2.1.5
  yaml: ^2.2.1
dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.5
