name: example
description: An example that demonstrates how to add a custom configuration file loader.
repository: https://github.com/just95/toml.dart/tree/main/example/custom_config_loader
publish_to: none
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  pedantic: ^1.9.0
  toml:
    path: ../../
